apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard-ingress
  name: kuard-ingress
  namespace: kuard-app
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard-ingress
  type: ClusterIP
