apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cartographer-workshop-role
rules:
  - apiGroups: [source.toolkit.fluxcd.io]
    resources: [gitrepositories]
    verbs: ['*']
  - apiGroups: [kpack.io]
    resources: [images]
    verbs: ['*']
  - apiGroups: [kappctrl.k14s.io]
    resources: [apps]
    verbs: ["*"]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: ['*']
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: ['*']
  - apiGroups: [""]
    resources: [services]
    verbs: ['*']
