apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-supply-chain-source-to-deployment
rules:
  - apiGroups: [apps]
    resources: [deployments]
    verbs: ['*']
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: ['*']
  - apiGroups: [""]
    resources: [services]
    verbs: ['*']
