apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kapp-controller-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
  - apiGroups: [kappctrl.k14s.io]
    resources: [apps]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kapp-controller-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kapp-controller-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
