#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: cartographer-workshop-supply-chain
spec:
  selector:
    apps.tanzu.vmware.com/workload-type: source-to-ingress

  params:
    - name: registry
      default: #@ data.values.registry

  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: cartographer-workshop-git-repository-template

    - name: image-builder
      templateRef:
        kind: ClusterImageTemplate
        name: #@ data.values.image_template
      sources:
        - resource: source-provider
          name: source
