#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def/end deployment():
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuard-ingress
  name: kuard-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuard-ingress
  template:
    metadata:
      labels:
        app: kuard-ingress
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: kuard

#@ def/end service():
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuard-ingress
  name: kuard-ingress
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: kuard-ingress
  type: ClusterIP

#@ def/end ingress():
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kuard-ingress
  labels:
    app: ingress
spec:
  rules:
  - host: kuard-ingress.127-0-0-1.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kuard-ingress
            port:
              number: 8080

---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: nginx-ingress
spec:
  serviceAccountName: default
  fetch:
  - inline:
      paths:
        deployment.yml : #@ yaml.encode(deployment())
        service.yml : #@ yaml.encode(service())
        ingress.yml : #@ yaml.encode(ingress())
  template:
  - ytt: {}
  deploy:
  - kapp: {}
