#@ load("@ytt:data", "data")
---
apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: cartographer-workshop-supply-chain
spec:
  selector:
    apps.tanzu.vmware.com/workload-type: source-to-ingress

  serviceAccountRef:
    name: #@ data.values.service_account
    namespace: #@ data.values.namespace

  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: cartographer-workshop-git-repository-template
